services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Монтируем папку для логов
      - ./logs:/app/logs
      # Hot reload: монтируем только файлы Python для автоматической перезагрузки
      - ./backend/main.py:/app/main.py
      - ./backend/logic.py:/app/logic.py
      - ./frontend:/app/frontend
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]