services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Монтируем папку для логов
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
